# Includes complete Jenkins configuration in order to run croc-hunter pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  Memory: "512Mi"
  HostName: jenkins.acs.az.estrado.io
  ServiceType: ClusterIP
  InstallPlugins:
      - kubernetes:0.11 
      - workflow-aggregator:2.5
      - credentials-binding:1.12
      - git:3.3.1
      - pipeline-github-lib:1.0
      - ghprb:1.39.0
      - blueocean:1.1.4

  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"

  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"

    TLS:
      - secretName: jenkins.acs.az.estrado.io
        hosts:
          - jenkins.acs.az.estrado.io

Agent:
  Enabled: false
