apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"
  type: {{ default "ClusterIP" .Values.serviceType | quote }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  replicas: {{ default 1 .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.component}}"
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ template "fullname" . }}
          image: "{{.Values.image}}:{{.Values.imageTag}}"
          imagePullPolicy: "{{.Values.imagePullPolicy}}"
          ports:
          - name: http
            containerPort: {{.Values.containerPort}}
          resources:
            requests:
              cpu: "{{.Values.cpu}}"
              memory: "{{.Values.memory}}"
          env:
          - name: WORKFLOW_RELEASE
            value: {{.Release.Name | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
