apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-tests
data:
  run.sh: |-
    @test "Testing Croc Hunter is accessible" {
      curl --retry 3 --retry-delay 10 {{ template "fullname" . }}:{{.Values.servicePort}}
    }
