---
  apiVersion: helm.integrations.flux.weave.works/v1alpha
  kind: FluxHelmRelease
  metadata:
    name: mariadb
    namespace: default
    labels:
      chart: mariadb
  spec:
    chartGitPath: mariadb
    values:
      - name: image
        value: bitnami/mariadb:10.1.30-r1
      - name: persistence.enabled
        value: false
